export const DEFAULT_LOCALE = 'en';

export const CHANGE_MENU_STATE = 'App/CHANGE_MENU_STATE';
export const CHANGE_HOMEPAGE_STATE = 'App/CHANGE_HOMEPAGE_STATE';
export const SAVE_TOKEN = 'App/SAVE_TOKEN';
export const ADD_LAST_VIEWED_DESIGN = 'App/ADD_LAST_VIEWED_DESIGN';
